import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/myComponents/Navbar";

import { Comic_Relief } from "next/font/google";
import CheckAuth from "@/myComponents/hoc/CheckAuth";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "4UWpzGbWa2Ay5avi0nm3Gk6r724QeZE-2WfLwui3C4I",
  },
};

const comicRelif = Comic_Relief({
  weight: ["700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="coffee" lang="en" suppressHydrationWarning>
      {/* Google Analytics */}
      <Script src="https://www.googletagmanager.com/gtag/js?id=G-MPXQSDP7VZ" strategy="afterInteractive" />
      <Script id="ga" strategy="afterInteractive">
        {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-MPXQSDP7VZ');
          `}
      </Script>
      <body className={`${comicRelif.className} scroll-smooth overflow-x-hidden`}>
        <main>
          <CheckAuth>
            <Navbar />
            {children}
          </CheckAuth>
        </main>
      </body>
    </html>
  );
}
