import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/myComponents/Navbar";

import { Comic_Relief } from "next/font/google";
import CheckAuth from "@/myComponents/hoc/CheckAuth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "4UWpzGbWa2Ay5avi0nm3Gk6r724QeZE-2WfLwui3C4I",
  },
};

const comicRelif = Comic_Relief({
  weight: ["700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="coffee" lang="en" suppressHydrationWarning>
      <body className={`${comicRelif.className} scroll-smooth overflow-x-hidden`}>
        <main>
          <CheckAuth>
            <Navbar />
            {children}
          </CheckAuth>
        </main>
      </body>
    </html>
  );
}
